version: 0.2
phases:
  # install:
  #   runtime-versions:
  #     java: corretto11
  # pre_build:
  #   commands:
  #     - java -version
  #     # - mvn surefire-report:report
  # build:
  #   commands:
  #     - mvn surefire-report:report
  #     - mvn -X package
  post_build:
    commands:
      - cp automation/appspec.yaml appspec.yaml 
      # - sam build -t infrastructure/infrastructure.yaml
      # - sam package -t .aws-sam/build/template.yaml --s3-bucket pipeline-petclinic --output-template-file template.yaml

# reports: #New
#   SurefireReportsGroup: # CodeBuild will create a report group called "SurefireReports".
#     files: #Store all of the files
#       - '**/*'
#     base-directory: 'target/surefire-reports' # Location of the reports 
artifacts:
  files:
    # - template.yaml
    # - infrastructure/config/*
    # - target/spring-petclinic-2.7.0-SNAPSHOT.jar
    # - hooks/*
    - appspec.yaml